"""Common utilities"""

import pandas as pd

from scripts.config import Paths
from scripts.logger import logger
from scripts.get_raw_data import fetch_ghed_data


def read_ghed_data() -> pd.DataFrame:

    path = Paths.raw_data / "ghed_data.csv"

    if not path.exists():
        logger.info("GHED data not found, fetching...")
        fetch_ghed_data()

    logger.info("Reading GHED data...")
    return pd.read_csv(path)


FY22_INCOME_DICT = {
    "AFG": "Low income",
    "ALB": "Upper middle income",
    "DZA": "Lower middle income",
    "ASM": "Upper middle income",
    "AND": "High income",
    "AGO": "Lower middle income",
    "ATG": "High income",
    "ARG": "Upper middle income",
    "ARM": "Upper middle income",
    "ABW": "High income",
    "AUS": "High income",
    "AUT": "High income",
    "AZE": "Upper middle income",
    "BHS": "High income",
    "BHR": "High income",
    "BGD": "Lower middle income",
    "BRB": "High income",
    "BLR": "Upper middle income",
    "BEL": "High income",
    "BLZ": "Lower middle income",
    "BEN": "Lower middle income",
    "BMU": "High income",
    "BTN": "Lower middle income",
    "BOL": "Lower middle income",
    "BIH": "Upper middle income",
    "BWA": "Upper middle income",
    "BRA": "Upper middle income",
    "VGB": "High income",
    "BRN": "High income",
    "BGR": "Upper middle income",
    "BFA": "Low income",
    "BDI": "Low income",
    "CPV": "Lower middle income",
    "KHM": "Lower middle income",
    "CMR": "Lower middle income",
    "CAN": "High income",
    "CYM": "High income",
    "CAF": "Low income",
    "TCD": "Low income",
    "CHI": "High income",
    "CHL": "High income",
    "CHN": "Upper middle income",
    "COL": "Upper middle income",
    "COM": "Lower middle income",
    "COD": "Low income",
    "COG": "Lower middle income",
    "CRI": "Upper middle income",
    "CIV": "Lower middle income",
    "HRV": "High income",
    "CUB": "Upper middle income",
    "CUW": "High income",
    "CYP": "High income",
    "CZE": "High income",
    "DNK": "High income",
    "DJI": "Lower middle income",
    "DMA": "Upper middle income",
    "DOM": "Upper middle income",
    "ECU": "Upper middle income",
    "EGY": "Lower middle income",
    "SLV": "Lower middle income",
    "GNQ": "Upper middle income",
    "ERI": "Low income",
    "EST": "High income",
    "SWZ": "Lower middle income",
    "ETH": "Low income",
    "FRO": "High income",
    "FJI": "Upper middle income",
    "FIN": "High income",
    "FRA": "High income",
    "PYF": "High income",
    "GAB": "Upper middle income",
    "GMB": "Low income",
    "GEO": "Upper middle income",
    "DEU": "High income",
    "GHA": "Lower middle income",
    "GIB": "High income",
    "GRC": "High income",
    "GRL": "High income",
    "GRD": "Upper middle income",
    "GUM": "High income",
    "GTM": "Upper middle income",
    "GIN": "Low income",
    "GNB": "Low income",
    "GUY": "Upper middle income",
    "HTI": "Lower middle income",
    "HND": "Lower middle income",
    "HKG": "High income",
    "HUN": "High income",
    "ISL": "High income",
    "IND": "Lower middle income",
    "IDN": "Lower middle income",
    "IRN": "Lower middle income",
    "IRQ": "Upper middle income",
    "IRL": "High income",
    "IMN": "High income",
    "ISR": "High income",
    "ITA": "High income",
    "JAM": "Upper middle income",
    "JPN": "High income",
    "JOR": "Upper middle income",
    "KAZ": "Upper middle income",
    "KEN": "Lower middle income",
    "KIR": "Lower middle income",
    "PRK": "Low income",
    "KOR": "High income",
    "XKX": "Upper middle income",
    "KWT": "High income",
    "KGZ": "Lower middle income",
    "LAO": "Lower middle income",
    "LVA": "High income",
    "LBN": "Upper middle income",
    "LSO": "Lower middle income",
    "LBR": "Low income",
    "LBY": "Upper middle income",
    "LIE": "High income",
    "LTU": "High income",
    "LUX": "High income",
    "MAC": "High income",
    "MDG": "Low income",
    "MWI": "Low income",
    "MYS": "Upper middle income",
    "MDV": "Upper middle income",
    "MLI": "Low income",
    "MLT": "High income",
    "MHL": "Upper middle income",
    "MRT": "Lower middle income",
    "MUS": "Upper middle income",
    "MEX": "Upper middle income",
    "FSM": "Lower middle income",
    "MDA": "Upper middle income",
    "MCO": "High income",
    "MNG": "Lower middle income",
    "MNE": "Upper middle income",
    "MAR": "Lower middle income",
    "MOZ": "Low income",
    "MMR": "Lower middle income",
    "NAM": "Upper middle income",
    "NRU": "High income",
    "NPL": "Lower middle income",
    "NLD": "High income",
    "NCL": "High income",
    "NZL": "High income",
    "NIC": "Lower middle income",
    "NER": "Low income",
    "NGA": "Lower middle income",
    "MKD": "Upper middle income",
    "MNP": "High income",
    "NOR": "High income",
    "OMN": "High income",
    "PAK": "Lower middle income",
    "PLW": "High income",
    "PAN": "Upper middle income",
    "PNG": "Lower middle income",
    "PRY": "Upper middle income",
    "PER": "Upper middle income",
    "PHL": "Lower middle income",
    "POL": "High income",
    "PRT": "High income",
    "PRI": "High income",
    "QAT": "High income",
    "ROU": "Upper middle income",
    "RUS": "Upper middle income",
    "RWA": "Low income",
    "WSM": "Lower middle income",
    "SMR": "High income",
    "STP": "Lower middle income",
    "SAU": "High income",
    "SEN": "Lower middle income",
    "SRB": "Upper middle income",
    "SYC": "High income",
    "SLE": "Low income",
    "SGP": "High income",
    "SXM": "High income",
    "SVK": "High income",
    "SVN": "High income",
    "SLB": "Lower middle income",
    "SOM": "Low income",
    "ZAF": "Upper middle income",
    "SSD": "Low income",
    "ESP": "High income",
    "LKA": "Lower middle income",
    "KNA": "High income",
    "LCA": "Upper middle income",
    "MAF": "High income",
    "VCT": "Upper middle income",
    "SDN": "Low income",
    "SUR": "Upper middle income",
    "SWE": "High income",
    "CHE": "High income",
    "SYR": "Low income",
    "TWN": "High income",
    "TJK": "Lower middle income",
    "TZA": "Lower middle income",
    "THA": "Upper middle income",
    "TLS": "Lower middle income",
    "TGO": "Low income",
    "TON": "Upper middle income",
    "TTO": "High income",
    "TUN": "Lower middle income",
    "TUR": "Upper middle income",
    "TKM": "Upper middle income",
    "TCA": "High income",
    "TUV": "Upper middle income",
    "UGA": "Low income",
    "UKR": "Lower middle income",
    "ARE": "High income",
    "GBR": "High income",
    "USA": "High income",
    "URY": "High income",
    "UZB": "Lower middle income",
    "VUT": "Lower middle income",
    "VNM": "Lower middle income",
    "VIR": "High income",
    "PSE": "Lower middle income",
    "YEM": "Low income",
    "ZMB": "Lower middle income",
    "ZWE": "Lower middle income",
}


def add_income_fy22(
    df: pd.DataFrame,
    iso3_col: str = "iso3_code",
    income_level_col: str = "income_level",
) -> pd.DataFrame:
    """Add FY22 income level to a dataframe based on ISO3 codes"""

    return df.assign(**{income_level_col: df[iso3_col].map(FY22_INCOME_DICT)})


FY23_INCOME_DICT = {
    **FY22_INCOME_DICT,
    # Upgrades
    "BLZ": "Upper middle income",   # was Lower middle income
    "PAN": "High income",           # was Upper middle income
    "ROU": "High income",           # was Upper middle income
    # Downgrades
    "LBN": "Lower middle income",   # was Upper middle income
    "PLW": "Upper middle income",   # was High income
    "ZMB": "Low income",            # was Lower middle income
}


def add_income_fy23(
    df: pd.DataFrame,
    iso3_col: str = "iso3_code",
    income_level_col: str = "income_level",
) -> pd.DataFrame:
    """Add FY23 income level to a dataframe based on ISO3 codes"""

    return df.assign(**{income_level_col: df[iso3_col].map(FY23_INCOME_DICT)})
